services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: checkbook-postgres-dev
    environment:
      POSTGRES_DB: checkbook
      POSTGRES_USER: checkbook_user
      POSTGRES_PASSWORD: checkbook_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - checkbook-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkbook_user -d checkbook"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for rate limiting and caching
  redis:
    image: redis:7-alpine
    container_name: checkbook-redis-dev
    ports:
      - "6379:6379"
    networks:
      - checkbook-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: checkbook-mailhog-dev
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - checkbook-dev-network

networks:
  checkbook-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local